### ISSUE TITLE
.mbedignore should be removed

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-atecc608a#30]
During 5.15 OOB, I found that we're using .mbedignore in this example:
https://github.com/ARMmbed/mbed-os-example-atecc608a/blob/mbed-os-5.15/.mbedignore

This is essentially removing 'unity':
https://github.com/ARMmbed/mbed-os/tree/master/features/frameworks/unity

It shouldn't be required to use .mbedignore as it's considered a hack. If this 'unity' component is really required, it would create problems for developers when starting to develop applications from scratch just using the standard API in Mbed OS.

Please consider removing this file. If required a fix in Mbed OS, please raise an issue/PR there as well.

@Patater @adbridge

**Comment by adbridge** [comment]
I wouldn't consider this a blocker for the release but @Patater should probably be considered at least a Major.

**Comment by Patater** [comment]
The issue is that the library we use to access the hardware, cryptoauthlib (from Microchip), and Mbed OS both include their own copy of the Unity test framework. The versions of Unity shipped with each can even be different (they aren't guaranteed to be compatible versions). To fix this, given that we have a build system that seeks out all source code, we need either component to remove their duplicate copy of Unity (not practicable) or tell the Mbed OS build system to not include cryptoauthlib's copy of Unity and any code in cryptoauthlib that depends on Unity.

We currently ignore cryptoauthlib's copy and dependent code in our wrapper of cryptoauthlib that enables cryptoauthlib to build with Mbed OS build tools: https://github.com/ARMmbed/mbed-cryptoauthlib/blob/master/.mbedignore

We had `.mbedignore` in this example because we didn't always have our wrapper ignoring cryptoauthlib's Unity.

@MarceloSalazar Given that `.mbedignore` is a hack, what's the proper way to hide cryptoauthlib's copy of Unity from our Mbed OS build system?

**Comment by MarceloSalazar** [comment]
Thanks for clarifying this.
The solution to `.mbedignore` is something that should come as part of the enhancements on the build system in the near future.
FYI @madchutney please be aware of this.

**Comment by ciarmcom** [comment]
@MarceloSalazar thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?
